from header_common import *

###################################################
# header_troops.py
# This file contains declarations for troops
# DO NOT EDIT THIS FILE!
###################################################

#Troop flags
tf_male           = 0
tf_female         = 1
tf_undead         = 2
tf_beautiful      = 3
tf_tall           = 4
tf_giant          = 5
tf_demon          = 6
tf_skeleton       = 7
tf_succubus       = 8
troop_type_mask   = 0x0000000f
tf_hero              = 0x00000010
tf_inactive          = 0x00000020
tf_unkillable        = 0x00000040
tf_allways_fall_dead = 0x00000080
tf_no_capture_alive  = 0x00000100
tf_mounted           = 0x00000400 #Troop's movement speed on map is determined by riding skill.
tf_is_merchant       = 0x00001000 #When set, troop does not equip stuff he owns
tf_randomize_face    = 0x00008000 #randomize face at the beginning of the game.

tf_guarantee_boots            = 0x00100000
tf_guarantee_armor            = 0x00200000
tf_guarantee_helmet           = 0x00400000
tf_guarantee_gloves           = 0x00800000
tf_guarantee_horse            = 0x01000000
tf_guarantee_shield           = 0x02000000
tf_guarantee_ranged           = 0x04000000
tf_guarantee_polearm          = 0x08000000
tf_unmoveable_in_party_window = 0x10000000

# Character attributes...
ca_strength     = 0
ca_agility      = 1
ca_intelligence = 2
ca_charisma     = 3

wpt_one_handed_weapon = 0
wpt_two_handed_weapon = 1
wpt_polearm           = 2
wpt_archery           = 3
wpt_crossbow          = 4
wpt_throwing          = 5
wpt_firearm           = 6


#personality modifiers:
# courage 8 means neutral
courage_4  = 0x0004
courage_5  = 0x0005
courage_6  = 0x0006
courage_7  = 0x0007
courage_8  = 0x0008
courage_9  = 0x0009
courage_10 = 0x000A
courage_11 = 0x000B
courage_12 = 0x000C
courage_13 = 0x000D
courage_14 = 0x000E
courage_15 = 0x000F

aggresiveness_1  = 0x0010
aggresiveness_2  = 0x0020
aggresiveness_3  = 0x0030
aggresiveness_4  = 0x0040
aggresiveness_5  = 0x0050
aggresiveness_6  = 0x0060
aggresiveness_7  = 0x0070
aggresiveness_8  = 0x0080
aggresiveness_9  = 0x0090
aggresiveness_10 = 0x00A0
aggresiveness_11 = 0x00B0
aggresiveness_12 = 0x00C0
aggresiveness_13 = 0x00D0
aggresiveness_14 = 0x00E0
aggresiveness_15 = 0x00F0

is_bandit        = 0x0100
#-----------------------------------
#these also in sentences.py
tsf_site_id_mask = 0x0000ffff
tsf_entry_mask   = 0x00ff0000
tsf_entry_bits   = 16

def entry(n):
  return (((n) << tsf_entry_bits) & tsf_entry_mask)
#-------------------------------------

str_3            = bignum | 0x3
str_4            = bignum | 0x4
str_5            = bignum | 0x5
str_6            = bignum | 0x6
str_7            = bignum | 0x7
str_8            = bignum | 0x8
str_9            = bignum | 0x9
str_10           = bignum | 0xa
str_11           = bignum | 0xb
str_12           = bignum | 0xc
str_13           = bignum | 0xd
str_14           = bignum | 0xe
str_15           = bignum | 0xf
str_16           = bignum | 0x10
str_17           = bignum | 0x11
str_18           = bignum | 0x12
str_19           = bignum | 0x13
str_20           = bignum | 0x14
str_21           = bignum | 0x15
str_22           = bignum | 0x16
str_23           = bignum | 0x17
str_24           = bignum | 0x18
str_25           = bignum | 0x19
str_26           = bignum | 0x1a
str_27           = bignum | 0x1b
str_28           = bignum | 0x1c
str_29           = bignum | 0x1d
str_30           = bignum | 0x1e
str_31           = bignum | 0x1F
str_32           = bignum | 0x20
str_33           = bignum | 0x21
str_34           = bignum | 0x22
str_35           = bignum | 0x23
str_36           = bignum | 0x24
str_37           = bignum | 0x25
str_38           = bignum | 0x26
str_39           = bignum | 0x27
str_40           = bignum | 0x28
str_41           = bignum | 0x29
str_42           = bignum | 0x2A
str_43           = bignum | 0x2B
str_44           = bignum | 0x2C
str_45           = bignum | 0x2D
str_46           = bignum | 0x2E
str_47           = bignum | 0x2F
str_48           = bignum | 0x30
str_49           = bignum | 0x31
str_50           = bignum | 0x32
str_51           = bignum | 0x33
str_52           = bignum | 0x34
str_53           = bignum | 0x35
str_54           = bignum | 0x36
str_55           = bignum | 0x37
str_56           = bignum | 0x38
str_57           = bignum | 0x39
str_58           = bignum | 0x3A
str_59           = bignum | 0x3B
str_60           = bignum | 0x3C
str_61           = bignum | 0x3D
str_62           = bignum | 0x3E
str_63           = bignum | 0x3F
str_64           = bignum | 0x40
str_65           = bignum | 0x41
str_66           = bignum | 0x42
str_67           = bignum | 0x43
str_68           = bignum | 0x44
str_69           = bignum | 0x45
str_70           = bignum | 0x46
str_71           = bignum | 0x47
str_72           = bignum | 0x48
str_73           = bignum | 0x49
str_74           = bignum | 0x4A
str_75           = bignum | 0x4B
str_76           = bignum | 0x4C
str_77           = bignum | 0x4D
str_78           = bignum | 0x4E
str_79           = bignum | 0x4F
str_80           = bignum | 0x50
str_81           = bignum | 0x51
str_82           = bignum | 0x52
str_83           = bignum | 0x53
str_84           = bignum | 0x54
str_85           = bignum | 0x55
str_86           = bignum | 0x56
str_87           = bignum | 0x57
str_88           = bignum | 0x58
str_89           = bignum | 0x59
str_90           = bignum | 0x5A
str_91           = bignum | 0x5B
str_92           = bignum | 0x5C
str_93           = bignum | 0x5D
str_94           = bignum | 0x5E
str_95           = bignum | 0x5F
str_96           = bignum | 0x60
str_97           = bignum | 0x61
str_98           = bignum | 0x62
str_99           = bignum | 0x63
str_100           = bignum | 0x64
str_101           = bignum | 0x65
str_102           = bignum | 0x66
str_103           = bignum | 0x67
str_104           = bignum | 0x68
str_105           = bignum | 0x69
str_106           = bignum | 0x6A
str_107           = bignum | 0x6B
str_108           = bignum | 0x6C
str_109           = bignum | 0x6D
str_110           = bignum | 0x6E
str_111           = bignum | 0x6F
str_112           = bignum | 0x70
str_113           = bignum | 0x71
str_114           = bignum | 0x72
str_115           = bignum | 0x73
str_116           = bignum | 0x74
str_117           = bignum | 0x75
str_118           = bignum | 0x76
str_119           = bignum | 0x77
str_120           = bignum | 0x78
str_121           = bignum | 0x79
str_122           = bignum | 0x7A
str_123           = bignum | 0x7B
str_124           = bignum | 0x7C
str_125           = bignum | 0x7D
str_126           = bignum | 0x7E
str_127           = bignum | 0x7F
str_128           = bignum | 0x80
str_129           = bignum | 0x81
str_130           = bignum | 0x82
str_131           = bignum | 0x83
str_132           = bignum | 0x84
str_133           = bignum | 0x85
str_134           = bignum | 0x86
str_135           = bignum | 0x87
str_136           = bignum | 0x88
str_137           = bignum | 0x89
str_138           = bignum | 0x8A
str_139           = bignum | 0x8B
str_140           = bignum | 0x8C
str_141           = bignum | 0x8D
str_142           = bignum | 0x8E
str_143           = bignum | 0x8F
str_144           = bignum | 0x90
str_145           = bignum | 0x91
str_146           = bignum | 0x92
str_147           = bignum | 0x93
str_148           = bignum | 0x94
str_149           = bignum | 0x95
str_150           = bignum | 0x96
str_151           = bignum | 0x97
str_152           = bignum | 0x98
str_153           = bignum | 0x99
str_154           = bignum | 0x9A
str_155           = bignum | 0x9B
str_156           = bignum | 0x9C
str_157           = bignum | 0x9D
str_158           = bignum | 0x9E
str_159           = bignum | 0x9F
str_160           = bignum | 0xA0
str_161           = bignum | 0xA1
str_162           = bignum | 0xA2
str_163           = bignum | 0xA3
str_164           = bignum | 0xA4
str_165           = bignum | 0xA5
str_166           = bignum | 0xA6
str_167           = bignum | 0xA7
str_168           = bignum | 0xA8
str_169           = bignum | 0xA9
str_170           = bignum | 0xAA
str_171           = bignum | 0xAB
str_172           = bignum | 0xAC
str_173           = bignum | 0xAD
str_174           = bignum | 0xAE
str_175           = bignum | 0xAF
str_176           = bignum | 0xB0
str_177           = bignum | 0xB1
str_178           = bignum | 0xB2
str_179           = bignum | 0xB3
str_180           = bignum | 0xB4
str_181           = bignum | 0xB5
str_182           = bignum | 0xB6
str_183           = bignum | 0xB7
str_184           = bignum | 0xB8
str_185           = bignum | 0xB9
str_186           = bignum | 0xBA
str_187           = bignum | 0xBB
str_188           = bignum | 0xBC
str_189           = bignum | 0xBD
str_190           = bignum | 0xBE
str_191           = bignum | 0xBF
str_192           = bignum | 0xC0
str_193           = bignum | 0xC1
str_194           = bignum | 0xC2
str_195           = bignum | 0xC3
str_196           = bignum | 0xC4
str_197           = bignum | 0xC5
str_198           = bignum | 0xC6
str_199           = bignum | 0xC7
str_200           = bignum | 0xC8

agi_3           = bignum | 0x300
agi_4           = bignum | 0x400
agi_5           = bignum | 0x500
agi_6           = bignum | 0x600
agi_7           = bignum | 0x700
agi_8           = bignum | 0x800
agi_9           = bignum | 0x900
agi_10           = bignum | 0xA00
agi_11           = bignum | 0xB00
agi_12           = bignum | 0xC00
agi_13           = bignum | 0xD00
agi_14           = bignum | 0xE00
agi_15           = bignum | 0xF00
agi_16           = bignum | 0x1000
agi_17           = bignum | 0x1100
agi_18           = bignum | 0x1200
agi_19           = bignum | 0x1300
agi_20           = bignum | 0x1400
agi_21           = bignum | 0x1500
agi_22           = bignum | 0x1600
agi_23           = bignum | 0x1700
agi_24           = bignum | 0x1800
agi_25           = bignum | 0x1900
agi_26           = bignum | 0x1A00
agi_27           = bignum | 0x1B00
agi_28           = bignum | 0x1C00
agi_29           = bignum | 0x1D00
agi_30           = bignum | 0x1E00
agi_31           = bignum | 0x1F00
agi_32           = bignum | 0x2000
agi_33           = bignum | 0x2100
agi_34           = bignum | 0x2200
agi_35           = bignum | 0x2300
agi_36           = bignum | 0x2400
agi_37           = bignum | 0x2500
agi_38           = bignum | 0x2600
agi_39           = bignum | 0x2700
agi_40           = bignum | 0x2800
agi_41           = bignum | 0x2900
agi_42           = bignum | 0x2A00
agi_43           = bignum | 0x2B00
agi_44           = bignum | 0x2C00
agi_45           = bignum | 0x2D00
agi_46           = bignum | 0x2E00
agi_47           = bignum | 0x2F00
agi_48           = bignum | 0x3000
agi_49           = bignum | 0x3100
agi_50           = bignum | 0x3200
agi_51           = bignum | 0x3300
agi_52           = bignum | 0x3400
agi_53           = bignum | 0x3500
agi_54           = bignum | 0x3600
agi_55           = bignum | 0x3700
agi_56           = bignum | 0x3800
agi_57           = bignum | 0x3900
agi_58           = bignum | 0x3A00
agi_59           = bignum | 0x3B00
agi_60           = bignum | 0x3C00
agi_61           = bignum | 0x3D00
agi_62           = bignum | 0x3E00
agi_63           = bignum | 0x3F00
agi_64           = bignum | 0x4000
agi_65           = bignum | 0x4100
agi_66           = bignum | 0x4200
agi_67           = bignum | 0x4300
agi_68           = bignum | 0x4400
agi_69           = bignum | 0x4500
agi_70           = bignum | 0x4600
agi_71           = bignum | 0x4700
agi_72           = bignum | 0x4800
agi_73           = bignum | 0x4900
agi_74           = bignum | 0x4A00
agi_75           = bignum | 0x4B00
agi_76           = bignum | 0x4C00
agi_77           = bignum | 0x4D00
agi_78           = bignum | 0x4E00
agi_79           = bignum | 0x4F00
agi_80           = bignum | 0x5000
agi_81           = bignum | 0x5100
agi_82           = bignum | 0x5200
agi_83           = bignum | 0x5300
agi_84           = bignum | 0x5400
agi_85           = bignum | 0x5500
agi_86           = bignum | 0x5600
agi_87           = bignum | 0x5700
agi_88           = bignum | 0x5800
agi_89           = bignum | 0x5900
agi_90           = bignum | 0x5A00
agi_91           = bignum | 0x5B00
agi_92           = bignum | 0x5C00
agi_93           = bignum | 0x5D00
agi_94           = bignum | 0x5E00
agi_95           = bignum | 0x5F00
agi_96           = bignum | 0x6000
agi_97           = bignum | 0x6100
agi_98           = bignum | 0x6200
agi_99           = bignum | 0x6300
agi_100           = bignum | 0x6400
agi_101           = bignum | 0x6500
agi_102           = bignum | 0x6600
agi_103           = bignum | 0x6700
agi_104           = bignum | 0x6800
agi_105           = bignum | 0x6900
agi_106           = bignum | 0x6A00
agi_107           = bignum | 0x6B00
agi_108           = bignum | 0x6C00
agi_109           = bignum | 0x6D00
agi_110           = bignum | 0x6E00
agi_111           = bignum | 0x6F00
agi_112           = bignum | 0x7000
agi_113           = bignum | 0x7100
agi_114           = bignum | 0x7200
agi_115           = bignum | 0x7300
agi_116           = bignum | 0x7400
agi_117           = bignum | 0x7500
agi_118           = bignum | 0x7600
agi_119           = bignum | 0x7700
agi_120           = bignum | 0x7800
agi_121           = bignum | 0x7900
agi_122           = bignum | 0x7A00
agi_123           = bignum | 0x7B00
agi_124           = bignum | 0x7C00
agi_125           = bignum | 0x7D00
agi_126           = bignum | 0x7E00
agi_127           = bignum | 0x7F00
agi_128           = bignum | 0x8000
agi_129           = bignum | 0x8100
agi_130           = bignum | 0x8200
agi_131           = bignum | 0x8300
agi_132           = bignum | 0x8400
agi_133           = bignum | 0x8500
agi_134           = bignum | 0x8600
agi_135           = bignum | 0x8700
agi_136           = bignum | 0x8800
agi_137           = bignum | 0x8900
agi_138           = bignum | 0x8A00
agi_139           = bignum | 0x8B00
agi_140           = bignum | 0x8C00
agi_141           = bignum | 0x8D00
agi_142           = bignum | 0x8E00
agi_143           = bignum | 0x8F00
agi_144           = bignum | 0x9000
agi_145           = bignum | 0x9100
agi_146           = bignum | 0x9200
agi_147           = bignum | 0x9300
agi_148           = bignum | 0x9400
agi_149           = bignum | 0x9500
agi_150           = bignum | 0x9600


int_3           = bignum | 0x30000
int_4           = bignum | 0x40000
int_5           = bignum | 0x50000
int_6           = bignum | 0x60000
int_7           = bignum | 0x70000
int_8           = bignum | 0x80000
int_9           = bignum | 0x90000
int_10           = bignum | 0xA0000
int_11           = bignum | 0xB0000
int_12           = bignum | 0xC0000
int_13           = bignum | 0xD0000
int_14           = bignum | 0xE0000
int_15           = bignum | 0xF0000
int_16           = bignum | 0x100000
int_17           = bignum | 0x110000
int_18           = bignum | 0x120000
int_19           = bignum | 0x130000
int_20           = bignum | 0x140000
int_21           = bignum | 0x150000
int_22           = bignum | 0x160000
int_23           = bignum | 0x170000
int_24           = bignum | 0x180000
int_25           = bignum | 0x190000
int_26           = bignum | 0x1A0000
int_27           = bignum | 0x1B0000
int_28           = bignum | 0x1C0000
int_29           = bignum | 0x1D0000
int_30           = bignum | 0x1E0000
int_31           = bignum | 0x1F0000
int_32           = bignum | 0x200000
int_33           = bignum | 0x210000
int_34           = bignum | 0x220000
int_35           = bignum | 0x230000
int_36           = bignum | 0x240000
int_37           = bignum | 0x250000
int_38           = bignum | 0x260000
int_39           = bignum | 0x270000
int_40           = bignum | 0x280000
int_41           = bignum | 0x290000
int_42           = bignum | 0x2A0000
int_43           = bignum | 0x2B0000
int_44           = bignum | 0x2C0000
int_45           = bignum | 0x2D0000
int_46           = bignum | 0x2E0000
int_47           = bignum | 0x2F0000
int_48           = bignum | 0x300000
int_49           = bignum | 0x310000
int_50           = bignum | 0x320000
int_51           = bignum | 0x330000
int_52           = bignum | 0x340000
int_53           = bignum | 0x350000
int_54           = bignum | 0x360000
int_55           = bignum | 0x370000
int_56           = bignum | 0x380000
int_57           = bignum | 0x390000
int_58           = bignum | 0x3A0000
int_59           = bignum | 0x3B0000
int_60           = bignum | 0x3C0000
int_61           = bignum | 0x3D0000
int_62           = bignum | 0x3E0000
int_63           = bignum | 0x3F0000
int_64           = bignum | 0x400000

cha_3           = bignum | 0x3000000
cha_4           = bignum | 0x4000000
cha_5           = bignum | 0x5000000
cha_6           = bignum | 0x6000000
cha_7           = bignum | 0x7000000
cha_8           = bignum | 0x8000000
cha_9           = bignum | 0x9000000
cha_10           = bignum | 0xA000000
cha_11           = bignum | 0xB000000
cha_12           = bignum | 0xC000000
cha_13           = bignum | 0xD000000
cha_14           = bignum | 0xE000000
cha_15           = bignum | 0xF000000
cha_16           = bignum | 0x10000000
cha_17           = bignum | 0x11000000
cha_18           = bignum | 0x12000000
cha_19           = bignum | 0x13000000
cha_20           = bignum | 0x14000000
cha_21           = bignum | 0x15000000
cha_22           = bignum | 0x16000000
cha_23           = bignum | 0x17000000
cha_24           = bignum | 0x18000000
cha_25           = bignum | 0x19000000
cha_26           = bignum | 0x1A000000
cha_27           = bignum | 0x1B000000
cha_28           = bignum | 0x1C000000
cha_29           = bignum | 0x1D000000
cha_30           = bignum | 0x1E000000
cha_31           = bignum | 0x1F000000
cha_32           = bignum | 0x20000000
cha_33           = bignum | 0x21000000
cha_34           = bignum | 0x22000000
cha_35           = bignum | 0x23000000
cha_36           = bignum | 0x24000000
cha_37           = bignum | 0x25000000
cha_38           = bignum | 0x26000000
cha_39           = bignum | 0x27000000
cha_40           = bignum | 0x28000000
cha_41           = bignum | 0x29000000
cha_42           = bignum | 0x2A000000
cha_43           = bignum | 0x2B000000
cha_44           = bignum | 0x2C000000
cha_45           = bignum | 0x2D000000
cha_46           = bignum | 0x2E000000
cha_47           = bignum | 0x2F000000
cha_48           = bignum | 0x30000000
cha_49           = bignum | 0x31000000
cha_50           = bignum | 0x32000000
cha_51           = bignum | 0x33000000
cha_52           = bignum | 0x34000000
cha_53           = bignum | 0x35000000
cha_54           = bignum | 0x36000000
cha_55           = bignum | 0x37000000
cha_56           = bignum | 0x38000000
cha_57           = bignum | 0x39000000
cha_58           = bignum | 0x3A000000
cha_59           = bignum | 0x3B000000
cha_60           = bignum | 0x3C000000
cha_61           = bignum | 0x3D000000
cha_62           = bignum | 0x3E000000
cha_63           = bignum | 0x3F000000
cha_64           = bignum | 0x40000000


level_mask       = 0x000000FF
level_bits       = 32

def level(v):
  if (v > level_mask):
    v = level_mask
  return (bignum|v) << level_bits
  
def_attrib = str_5 | agi_5 | int_4 | cha_4

# Weapon proficiencies:
one_handed_bits = 0
two_handed_bits = 10
polearm_bits    = 20
archery_bits    = 30
crossbow_bits   = 40
throwing_bits   = 50
firearm_bits    = 60

num_weapon_proficiencies = 7
def wp_one_handed(x):
  return (((bignum | x) & 0x3FF) << one_handed_bits)
def wp_two_handed(x):
  return (((bignum | x) & 0x3FF) << two_handed_bits)
def wp_polearm(x):
  return (((bignum | x) & 0x3FF) << polearm_bits)
def wp_archery(x):
  return (((bignum | x) & 0x3FF) << archery_bits)
def wp_crossbow(x):
  return (((bignum | x) & 0x3FF) << crossbow_bits)
def wp_throwing(x):
  return (((bignum | x) & 0x3FF) << throwing_bits)
def wp_firearm(x):
  return (((bignum | x) & 0x3FF) << firearm_bits)

def find_troop(troops,troop_id):
  result = -1
  num_troops = len(troops)
  i_troop = 0
  while (i_troop < num_troops) and (result == -1):
    troop = troops[i_troop]
    if (troop[0] == troop_id):
      result = i_troop
    else:
      i_troop += 1
  return result



def upgrade(troops,troop1_id,troop2_id):
  troop1_no = find_troop(troops,troop1_id)
  troop2_no = find_troop(troops,troop2_id)
  if (troop1_no == -1):
    print "Error with upgrade def: Unable to find troop1-id: " + troop1_id
  elif (troop2_no == -1):
    print "Error with upgrade def: Unable to find troop2-id: " + troop2_id
  else:
    cur_troop = troops[troop1_no]
    cur_troop_length = len(cur_troop)
    if cur_troop_length == 11:
      cur_troop[11:11] = [0, 0, 0, troop2_no, 0]
    elif cur_troop_length == 12:
      cur_troop[12:12] = [0, 0, troop2_no, 0]
    elif cur_troop_length == 13:
      cur_troop[13:13] = [0, troop2_no, 0]
    else:
      cur_troop[14:14] = [troop2_no, 0]
      

def upgrade2(troops,troop1_id,troop2_id,troop3_id):
  troop1_no = find_troop(troops,troop1_id)
  troop2_no = find_troop(troops,troop2_id)
  troop3_no = find_troop(troops,troop3_id)
  if (troop1_no == -1):
    print "Error with upgrade2 def: Unable to find troop1-id: " + troop1_id
  elif (troop2_no == -1):
    print "Error with upgrade2 def: Unable to find troop2-id: " + troop2_id
  elif (troop3_no == -1):
    print "Error with upgrade2 def: Unable to find troop3-id: " + troop3_id
  else:
    cur_troop = troops[troop1_no]
    cur_troop_length = len(cur_troop)
    if cur_troop_length == 11:
      cur_troop[11:11] = [0, 0, 0, troop2_no, troop3_no]
    elif cur_troop_length == 12:
      cur_troop[12:12] = [0, 0, troop2_no, troop3_no]
    elif cur_troop_length == 13:
      cur_troop[13:13] = [0, troop2_no, troop3_no]
    else:
      cur_troop[14:14] = [troop2_no, troop3_no]
